drone_inventory/authentication/routes.py
from flask import Blueprint, flash, render_template, request, redirect, url_for, flash
from flask_login import login_user, login_required, logout_user
from drone_inventory.forms import UserLoginForm
from drone_inventory.models import User, db, check_password_hash


auth = Blueprint('auth', __name__, template_folder='auth_templates')


@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        print(email, password)

        # Creating a new user instance and adding that user to the User Table
        user = User(email, password=password)
        db.session.add(user)
        db.session.commit()

        # Flashed message for successful sign up
        flash(f'You have successfully created a user account {email}', 'user-created')

        # Redirecting to signin page #
        return redirect(url_for('auth.signin'))

        
    return render_template('signup.html', form = form)


@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        print(email, password)

        logged_user = User.query.filter(User.email == email).first()
        if logged_user and check_password_hash(logged_user.password, password):
            login_user(logged_user)
            flash('You are successfully logged in.', 'auth-success')
            return redirect(url_for('site.home'))
        else:
            flash('Your Email/Password in incorrect', 'auth-failed')
            return redirect(url_for('auth.signin'))

    return render_template('signin.html', form = form)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

# def login_required(current_user):
#     def logout():
#         logout_user()
#         return redirect(url_for('site.home'))
#     if current_user.is_authenticated:
#         return logout()

drone_inventory/site/routes.py
from flask import Blueprint, render_template
from flask_login import login_required

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
@login_required
def profile():
    return render_template('profile.html')

drone_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Operators Drone Inventory</title>
</head>
<body>
    <!-- Navbar goes here -->
    <nav class="ct-nav">
        <div>
            <img src="../static/images/Coding Drones Logo.png" alt="">
        </div>
        <!-- Nav items beging here -->
        <div>
            <ul id="horizontal-list">
                <a href="{{ url_for('site.home') }}">
                    <li>The Coding Drones Project</li>
                </a>
                <a href="">
                    <li>Donate</li>
                </a>
                {% if current_user.is_authenticated %}
                    <a href="{{ url_for('site.profile') }}">
                        <li>Profile</li>
                    </a>
                    <a href="{{ url_for('auth.logout') }}">
                        <li>Log Out</li>
                    </a>
                {% else %}
                    <a href="{{ url_for('auth.signin') }}">
                        <li>Sign In</li>
                    </a>
                    <a href="{{ url_for('auth.signup') }}">
                        <li>Sign Up Free</li>
                    </a>
                {% endif %}
            </ul>
        </div>
    </nav>
    <!-- End of Nav -->

    {% block content %}
    
    {% endblock content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/js/bootstrap.min.js"></script>
</body>
</html>

drone_inventory/templates/form.html
<main class="container">
    <div class="row">
        <aside class="col-12 col-md-6">
            <h2>Create Your Free Account</h2>
            <!-- Most HTML produced by Flask Form Object --> 
            <form method="POST">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    <fieldset id="email-field">
                        {{ form.email.label }}
                        {{ form.email(class = "form-control", placeholder = "Place Email Here...") }}
                    </fieldset>
                    <fieldset id="password-field">
                        {{ form.password.label }}
                        {{ form.password(class = "form-control", placeholder = "Place Password Here...") }}
                    </fieldset>
                    <!-- Submit Field(Button) Here -->
                    {{ form.submit_button(class = "btn btn-primary btn-block") }}
                </div>
            </form>
        </aside>
    </div>
</main>